version: '3'
services:
  flask:
    container_name: flask-backend
    image: flask-backend
    build:
      context: .
      dockerfile: backend.Dockerfile
    env_file:
      - .env
    ports:
      - "5000:5000"
    networks:
      - app-network

  react:
    container_name: react-frontend
    image: react-frontend
    build:
      context: .
      dockerfile: frontend.Dockerfile
    env_file:
      - .env
    ports:
      - "80:80"
    networks:
      - app-network
    depends_on:
      - flask

networks:
  app-network:
