version: '3.8'

services:
  frontend:
    build:
      context: ../frontend
    ports:
      - "3000:3000"
    networks:
      - app_network
    environment:
      - REACT_APP_BACKEND_URL=http://backend:5000

  backend:
    build:
      context: ../backend
    ports:
      - "5000:5000"
    networks:
      - app_network
    env_file:
      - .env

networks:
  app_network:
    driver: bridge
