services:
  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "5000:5000"
    volumes:
      - ../backend:/app  # Utilisé principalement pour le développement
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - neo4j
    networks:
      - app-network

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
      args:
        REACT_APP_API_URL: ${REACT_APP_API_BASE_URL}  # Passe la variable d'environnement au build
    container_name: frontend
    ports:
      - "3000:3000"
    # Supprimez ou commentez le volume monté pour le frontend en production
    # volumes:
    #   - ../frontend:/app
    env_file:
      - .env  # Utilisé pour d'autres variables d'environnement si nécessaire
    depends_on:
      - backend
    networks:
      - app-network

  neo4j:
    image: neo4j:4.4
    container_name: neo4j
    ports:
      - "7474:7474"  # Interface web Neo4j
      - "7687:7687"  # Bolt protocol
    environment:
      - NEO4J_AUTH=neo4j/nAtZJb6PtTQshH-3x7fZBmu_0NxtxkMem8TgZFEh8ow  # Définir le mot de passe Neo4j
    volumes:
      - neo4j-data:/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  neo4j-data:
